import * as React from "react";

import { Card } from "@/components/ui/card";
import { cn } from "@/lib/utils";

// The console's one table. Thirteen of them were hand-rolled across ten files
// before this existed, each re-typing the same Card shell and the same
// `px-4 py-3` on every cell — 53 `<th>` elements, 37 of them carrying the
// byte-identical class string.
//
// ⚠ **THE STYLING IS SPLIT WITH `globals.css`, AND THAT IS NOT AN ACCIDENT.**
// The header's size and colour, the rule under it, the divider between rows,
// and the horizontal scroll all come from selectors keyed on
// `[data-slot="card"] table` — not from this file. They work on any table
// inside a Card, which is why the copies all looked alike despite sharing no
// code. What lives HERE is the part CSS cannot reach: the element structure and
// the cell rhythm. Change a border in `globals.css`; change padding here.
//
// ⚠ **NOT `components/ui/table.tsx`.** That path is regenerated by
// `npx shadcn add`, so the `px-4 py-3` rhythm below would be overwritten by the
// next person who adds an unrelated primitive. This is a first-party component
// and stays out of that directory. The short `Th`/`Td` names are also
// deliberate: shadcn's table primitive exports `TableHead` meaning a single
// `<th>`, and a file importing both would be a genuine trap.

// One cell's padding, and the single reason this component exists. Both `Th`
// and `Td` spend it, so a header can never drift out of step with the column
// beneath it — which is what "the header should have the same dimensions as the
// row" asks for, enforced rather than agreed.
const CELL = "px-4 py-3";

// The Card shell and the table itself.
//
// `tabIndex={0}` is load-bearing: `globals.css` gives a Card containing a
// table `overflow-x: auto`, and a scroll container that cannot be focused
// cannot be scrolled from the keyboard.
export function DataTable({
  className,
  ...props
}: React.ComponentProps<"table">) {
  return (
    <Card className="overflow-hidden p-0 gap-0" tabIndex={0}>
      <table className={cn("w-full text-sm", className)} {...props} />
    </Card>
  );
}

// The header: a `<thead>` and its single row, together.
//
// ⚠ **It takes no `className`, and that is the point.** The two elements are
// collapsed into one component so there is nowhere to hang a class on the
// header row — which is exactly how the deliveries table drifted, growing a
// `bg-muted/40` band and a `border-b` that doubled the rule `globals.css`
// already draws. A header that should look different everywhere belongs in
// the stylesheet; a header that should look different in ONE place is the bug
// this shape prevents.
export function THead({ children }: { children: React.ReactNode }) {
  return (
    <thead>
      <tr>{children}</tr>
    </thead>
  );
}

// A header cell. Left-aligned unless told otherwise.
//
// Pass `className="text-center"` or `"text-right"` to override — `cn` merges
// through `tailwind-merge`, so the last alignment wins rather than the two
// fighting. An empty one (`<Th />`) is how the action columns reserve their
// space; it carries `font-medium` like the rest and renders the same, because
// a font weight on no text is nothing.
export function Th({ className, ...props }: React.ComponentProps<"th">) {
  return (
    <th className={cn(CELL, "text-left font-medium", className)} {...props} />
  );
}

// ⚠ **THERE IS DELIBERATELY NO `TBody` OR `Tr`.** Call sites write `<tbody>`
// and `<tr>` directly. Neither carries a single class — the row divider is a
// `globals.css` selector, not a class on the row — so wrapping them would be
// indirection with nothing behind it, and an import to resolve before a reader
// learns that. The rule here is that a component in this file exists because it
// owns styling; if `<tr>` ever earns some, it gets one.

// A body cell, carrying the same padding as the header cell above it.
//
// Everything else — `text-xs`, `text-muted-foreground`, `whitespace-nowrap`,
// `font-medium`, `text-right` — arrives through `className`. Deliberately not
// a prop each: those combinations appear in a dozen shapes across the console,
// and a prop language for them would be a second dialect of Tailwind that the
// next person has to learn before they can write a cell.
export function Td({ className, ...props }: React.ComponentProps<"td">) {
  return <td className={cn(CELL, className)} {...props} />;
}
