//! The shape a service describes its `/v1` lanes in, and the OpenAPI
//! document built from those descriptions.
//!
//! **No hand-written spec and no handler annotations.** A service publishes a
//! table of [`Route`] and its router is BUILT by folding over it, so a lane the
//! document does not describe is a lane the service does not serve.
//! `contract/openapi.json` is generated by `make contract` and pinned by
//! `tests/openapi_contract.rs`.

use serde_json::{Map, Value, json};

/// The one HTTP method a [`Route`] answers. `/v1` has no PUT and no PATCH,
/// and their absence is the contract: nothing here is updated in place.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Method {
    /// A read.
    Get,
    /// The same read with no body — whether the thing is there at all.
    Head,
    /// A create — the only write shape `/v1` has.
    Post,
    /// A delete, which answers 204 and carries no body.
    Delete,
}

impl Method {
    /// The OpenAPI key for this method, which is lowercase.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Get => "get",
            Self::Head => "head",
            Self::Post => "post",
            Self::Delete => "delete",
        }
    }
}

/// One parameter a route takes, in the path or the query string.
#[derive(Debug, Clone, Copy)]
pub struct Param {
    /// The spelling a caller types.
    pub name: &'static str,
    /// True for a query parameter, false for one in the path.
    pub in_query: bool,
    /// Whether the lane refuses the request without it.
    pub required: bool,
    /// What it selects, in customer words.
    pub description: &'static str,
}

/// One answer a route gives, with the sentence saying when.
#[derive(Debug, Clone, Copy)]
pub struct Answer {
    /// The HTTP status.
    pub status: u16,
    /// When the lane gives it.
    pub description: &'static str,
}

/// One `/v1` lane.
#[derive(Debug, Clone, Copy)]
pub struct Route {
    /// The one method this lane answers.
    pub method: Method,
    /// The path as axum spells it, `{id}` braces included.
    pub path: &'static str,
    /// A noun phrase, for a list of lanes.
    pub summary: &'static str,
    /// What a caller needs that the signature does not say.
    pub description: &'static str,
    /// What it takes, in the path and the query string.
    pub params: &'static [Param],
    /// Every answer it gives, refusals included.
    pub answers: &'static [Answer],
    /// Whether a `telmoni_` bearer opens it. A lane that sets it false is
    /// documented as taking no credential and never answering 401.
    pub bearer: bool,
}

/// The document, from every service's table.
#[must_use]
pub fn document(
    title: &str,
    version: &str,
    server: &str,
    universal: &[Answer],
    routes: &[Route],
) -> Value {
    let mut paths: Map<String, Value> = Map::new();
    for route in routes {
        let entry = paths
            .entry(route.path.to_owned())
            .or_insert_with(|| json!({}));
        if let Some(obj) = entry.as_object_mut() {
            obj.insert(
                route.method.as_str().to_owned(),
                operation(route, universal),
            );
        }
    }

    json!({
        "openapi": "3.1.0",
        "info": {
            "title": title,
            "version": version,
            "description":
                "The API a `telmoni_` token opens. Every response that is not a \
                 success is an RFC 9457 problem document, and a client \
                 switches on its `type` rather than on its prose.",
        },
        "servers": [{ "url": server }],
        "security": [{ "bearerAuth": [] }],
        "paths": paths,
        "components": {
            "securitySchemes": {
                "bearerAuth": {
                    "type": "http",
                    "scheme": "bearer",
                    "description":
                        "A `telmoni_` API token, minted on the Keys page. The token \
                         IS the organization; there is no second credential and no \
                         scope below the organization.",
                },
            },
            "schemas": { "Problem": problem_schema() },
        },
    })
}

fn operation(route: &Route, universal: &[Answer]) -> Value {
    let params: Vec<Value> = route
        .params
        .iter()
        .map(|p| {
            json!({
                "name": p.name,
                "in": if p.in_query { "query" } else { "path" },
                "required": p.required,
                "description": p.description,
                "schema": { "type": "string" },
            })
        })
        .collect();

    let mut responses: Map<String, Value> = Map::new();
    let universal = universal.iter().filter(|a| route.bearer || a.status != 401);
    for answer in universal.chain(route.answers) {
        let content = if answer.status < 400 {
            json!({})
        } else {
            json!({
                "content": {
                    "application/problem+json": {
                        "schema": { "$ref": "#/components/schemas/Problem" },
                    },
                },
            })
        };
        let mut value = json!({ "description": answer.description });
        if let (Some(v), Some(c)) = (value.as_object_mut(), content.as_object()) {
            for (k, item) in c {
                v.insert(k.clone(), item.clone());
            }
        }
        responses.insert(answer.status.to_string(), value);
    }

    let mut op = json!({
        "summary": route.summary,
        "description": route.description,
        "responses": responses,
    });
    if let Some(obj) = op.as_object_mut() {
        if !params.is_empty() {
            obj.insert("parameters".into(), Value::Array(params));
        }
        if !route.bearer {
            obj.insert("security".into(), json!([]));
        }
    }
    op
}

/// RFC 9457, as `error_schema::ProblemDetails` serializes it.
fn problem_schema() -> Value {
    json!({
        "type": "object",
        "required": ["type", "title", "status"],
        "additionalProperties": true,
        "properties": {
            "type": {
                "type": "string",
                "description":
                    "The stable category URI. Switch on this, never on `title`.",
            },
            "title": { "type": "string" },
            "status": { "type": "integer" },
            "detail": { "type": "string" },
            "instance": { "type": "string" },
        },
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    const UNIVERSAL: &[Answer] = &[Answer {
        status: 401,
        description: "No credential.",
    }];

    const ONE: &[Route] = &[
        Route {
            method: Method::Get,
            bearer: true,
            path: "/v1/thing/{id}",
            summary: "One thing",
            description: "The thing.",
            params: &[Param {
                name: "id",
                in_query: false,
                required: true,
                description: "Which thing.",
            }],
            answers: &[
                Answer {
                    status: 200,
                    description: "The thing.",
                },
                Answer {
                    status: 404,
                    description: "No such thing.",
                },
            ],
        },
        Route {
            method: Method::Delete,
            bearer: true,
            path: "/v1/thing/{id}",
            summary: "Delete one thing",
            description: "Gone.",
            params: &[],
            answers: &[Answer {
                status: 204,
                description: "Gone.",
            }],
        },
    ];

    /// A lane reached before the caller holds a token: the document must not
    /// say it needs one, nor list a refusal it cannot give.
    #[test]
    fn a_lane_with_no_bearer_takes_no_credential_and_never_answers_401() {
        const OPEN: &[Route] = &[Route {
            method: Method::Post,
            bearer: false,
            path: "/v1/open",
            summary: "Open",
            description: "No token yet.",
            params: &[],
            answers: &[Answer {
                status: 202,
                description: "Pending.",
            }],
        }];
        let doc = document("T", "1", "https://example.test", UNIVERSAL, OPEN);
        let op = &doc["paths"]["/v1/open"]["post"];
        assert_eq!(op["security"], serde_json::json!([]));
        assert!(op["responses"]["401"].is_null(), "{op}");
        assert!(op["responses"]["202"].is_object());

        let doc = document("T", "1", "https://example.test", UNIVERSAL, ONE);
        let op = &doc["paths"]["/v1/thing/{id}"]["get"];
        assert!(op["security"].is_null());
        assert!(op["responses"]["401"].is_object());
    }

    #[test]
    fn two_methods_on_one_path_are_two_operations_under_one_key() {
        let doc = document("T", "1", "https://example.test", UNIVERSAL, ONE);
        let path = &doc["paths"]["/v1/thing/{id}"];
        assert!(path["get"].is_object());
        assert!(path["delete"].is_object());
        assert_eq!(doc["paths"].as_object().unwrap().len(), 1);
    }

    #[test]
    fn a_refusal_is_a_problem_document_and_a_success_is_not() {
        let doc = document("T", "1", "https://example.test", UNIVERSAL, ONE);
        let get = &doc["paths"]["/v1/thing/{id}"]["get"];
        assert_eq!(
            get["responses"]["404"]["content"]["application/problem+json"]["schema"]["$ref"],
            "#/components/schemas/Problem"
        );
        assert!(
            get["responses"]["200"].get("content").is_none(),
            "a success body is the wire contract's to describe, not this file's"
        );
    }

    #[test]
    fn a_path_parameter_and_a_query_parameter_are_told_apart() {
        const Q: &[Route] = &[Route {
            method: Method::Get,
            bearer: true,
            path: "/v1/thing",
            summary: "Things",
            description: "The things.",
            params: &[Param {
                name: "organization",
                in_query: true,
                required: false,
                description: "Whose.",
            }],
            answers: &[Answer {
                status: 200,
                description: "The things.",
            }],
        }];
        let doc = document("T", "1", "https://example.test", UNIVERSAL, Q);
        let param = &doc["paths"]["/v1/thing"]["get"]["parameters"][0];
        assert_eq!(param["in"], "query");
        assert_eq!(param["required"], false);
    }

    #[test]
    fn a_universal_answer_reaches_every_operation_and_a_lane_may_sharpen_it() {
        const SHARPER: &[Route] = &[Route {
            method: Method::Get,
            bearer: true,
            path: "/v1/thing",
            summary: "Things",
            description: "The things.",
            params: &[],
            answers: &[Answer {
                status: 401,
                description: "This lane says it better.",
            }],
        }];
        let doc = document("T", "1", "https://example.test", UNIVERSAL, ONE);
        assert_eq!(
            doc["paths"]["/v1/thing/{id}"]["delete"]["responses"]["401"]["description"],
            "No credential.",
            "a lane that never mentions 401 still documents it"
        );
        let doc = document("T", "1", "https://example.test", UNIVERSAL, SHARPER);
        assert_eq!(
            doc["paths"]["/v1/thing"]["get"]["responses"]["401"]["description"],
            "This lane says it better."
        );
    }

    #[test]
    fn every_operation_is_a_bearer_lane() {
        let doc = document("T", "1", "https://example.test", UNIVERSAL, ONE);
        assert_eq!(doc["security"][0]["bearerAuth"], json!([]));
        assert_eq!(
            doc["components"]["securitySchemes"]["bearerAuth"]["scheme"],
            "bearer"
        );
    }
}
