apiVersion: v1
kind: ServiceAccount
metadata:
  name: server
  labels:
    app.kubernetes.io/name: server
    {{- include "telmoni.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  labels:
    app.kubernetes.io/name: web
    {{- include "telmoni.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: migrator
  labels:
    app.kubernetes.io/name: migrator
    {{- include "telmoni.labels" . | nindent 4 }}
  {{- if and .Values.migrator.enabled .Values.migrator.hook.enabled }}
  {{- include "telmoni.migrateHookPrereq" . | nindent 2 }}
  {{- end }}
